spring.application.name=forohub

spring.datasource.url=${SDB_URL}
spring.datasource.username=${SDB_USER}
spring.datasource.password=${SDB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.error.include-stacktrace=never

server.port=8081

api.security.token.secret=${SJWT_SECRET}
api.security.token.issuer=forohub
api.security.token.expiration-hours=2
